version: '3.8'
services:
  keycloak:
    build: ./keycloak
    container_name: keycloak
    ports:
      - "8090:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start --optimized --import-realm
    networks:
      - club-network

networks:
  club-network:
    name: club-net
