spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/score
    username: admin
    password: admin
  flyway:
    locations: classpath:/db/migration/structure,classpath:/db/migration/sample
