spring:
  jpa:
    open-in-view: false
  flyway:
    locations: classpath:/db/migration/structure

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    java:
      enabled: true

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
