spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/score
    username: admin
    password: admin
  flyway:
    locations: classpath:/db/migration/structure,classpath:/db/migration/sample
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443/realms/score

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui
      client-secret: secret
      token-url: https://localhost:8443/realms/score/protocol/openid-connect/token

cors:
  allowed-origins:
    - "http://localhost:8080"
