spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:4321/realms/score
  datasource:
    # url is configured in `TestContainerConfiguration`
    username: admin
    password: pass
  flyway:
    locations: classpath:/db/migration/structure,classpath:/db/migration/sample

springdoc:
  swagger-ui:
    oauth:
      client-id: unused
      client-secret: unused
      token-url: http://unused

cors:
  allowed-origins:
    - "http://unused"
