# This workflow will build a Java/Kotlin project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI pipeline

on:
  push:
    branches:
    - main
    - feature/*
    - fix/*

permissions:
  contents: read

jobs:
  assemble:
    name: Assembles the Score Service
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Assemble with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble

  test:
    name: Tests the Score Service
    runs-on: ubuntu-latest
    needs: assemble

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
